import { useMemo, useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, MapPin, Search, ShieldCheck, Sparkles, Star, Store, X } from 'lucide-react';
import { getListProductsQueryKey, getListPromotionsQueryKey, useListProducts, useListPromotions } from '@api-client';
import { categories, Notice, PageHeading, ProductCard, SkeletonGrid } from '@/components/market';

export default function Storefront() {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('Todos');
  const [sort, setSort] = useState<'newest' | 'top'>('newest');
  const params = useMemo(() => ({ search: search.trim() || undefined, category: category === 'Todos' ? undefined : category, sort }), [search, category, sort]);
  const products = useListProducts(params, { query: { queryKey: getListProductsQueryKey(params), refetchInterval: 30_000, refetchOnWindowFocus: true } });
  const promotions = useListPromotions({ query: { queryKey: getListPromotionsQueryKey(), refetchInterval: 30_000, refetchOnWindowFocus: true } });
  const top = useListProducts({ sort: 'top' }, { query: { queryKey: getListProductsQueryKey({ sort: 'top' }), refetchInterval: 30_000, refetchOnWindowFocus: true } });
  const topRated = top.data?.filter(p => p.reviewCount > 0) ?? [];
  return <>
    <section className="bg-[#dfeae0] overflow-hidden relative">
      <div className="absolute top-[-180px] right-[-170px] w-[560px] h-[560px] rounded-full border-[90px] border-[#c9dfbb]/60 pointer-events-none"/>
      <div className="page-wrap relative grid lg:grid-cols-[1.05fr_.95fr] items-center gap-8 pt-12 pb-16 md:pt-20 md:pb-24">
         <div className="reveal max-w-[650px]"><div className="inline-flex items-center gap-2 bg-[#f8f9ef] rounded-full px-3 py-2 text-[#3d6b54] text-[11px] font-bold mb-7"><span className="h-2 w-2 bg-[#82af68] rounded-full"/> HECHO POR VECINOS, PARA VECINOS</div><h1 className="font-display text-[#294d64] text-[49px] leading-[1.04] sm:text-[68px] lg:text-[76px] tracking-[-.045em]">Todo lo bueno<br/>está <em className="text-[#64935b] not-italic">cerquita.</em></h1><p className="text-[#527078] text-[15px] sm:text-[17px] leading-relaxed max-w-[440px] mt-6">Ese postre que te contaron, un almuerzo hecho en casa, algo que necesitabas. Descúbrelo aquí, a unos pasos de tu puerta.</p><div className="flex flex-wrap gap-3 mt-8"><a href="#explorar" data-testid="link-discover" className="btn btn-primary">Explorar el mercado <ArrowRight size={16}/></a><Link href="/sell" data-testid="link-start-selling" className="btn btn-light">Quiero vender</Link></div><p className="flex items-center gap-2 mt-10 text-xs font-semibold text-[#5a7972]"><MapPin size={15}/> Pensado para Los Laureles · 4ta Etapa</p></div>
        <div className="relative flex justify-center lg:justify-end reveal" style={{animationDelay:'.15s'}}>
          <div className="relative bg-[#355c74] rounded-[34px] p-5 sm:p-7 w-full max-w-[470px] rotate-[-2deg] shadow-[15px_20px_0_#bbd4b6]">
            <div className="flex justify-between items-center mb-7"><span className="eyebrow text-[#cce4d1]">Nuestro pequeño mundo</span><Sparkles size={20} className="text-[#bbdd83]"/></div>
            <div className="rounded-2xl bg-[#2b516b] py-6 flex justify-center"><img src="/laureles-emblema.png" alt="Emblema del condominio Los Laureles" className="h-[176px] w-auto max-w-full mx-auto block object-contain"/></div>
            <div className="flex justify-between items-end mt-6 text-[#f5f9ec]"><div><p className="font-display text-2xl">De puerta a puerta.</p><p className="text-xs text-[#bdd4d0] mt-1">Más cerca, más nuestro.</p></div><div className="h-10 w-10 rounded-full bg-[#b9dd84] text-[#315344] flex items-center justify-center"><ArrowRight size={19}/></div></div>
          </div>
          <span className="absolute -bottom-6 -left-1 sm:left-2 bg-[#f9f9ed] rounded-xl px-4 py-3 text-xs text-[#355c74] font-bold shadow-lg rotate-[4deg]">La mejor tienda: tu vecino.</span>
        </div>
      </div>
    </section>
    <div className="page-wrap"><div className="grid md:grid-cols-3 border-b border-[#d6dfd9] py-7 gap-5 text-xs text-[#4d6c70] font-semibold"><span className="flex items-center gap-2"><Store size={17} className="text-[#73a164]"/> Compra directo a quien lo hace</span><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#73a164]"/> Acceso con cuenta personal</span><span className="flex items-center gap-2"><MapPin size={17} className="text-[#73a164]"/> Acuerdos de entrega entre vecinos</span></div></div>
    <section className="page-wrap pt-16" id="promociones"><div className="flex items-end justify-between gap-4 mb-7"><div><span className="eyebrow text-[#7c9d5e]">Un buen hallazgo</span><h2 className="font-display text-3xl sm:text-4xl text-[#294d64] mt-2">Destacados del barrio</h2></div><a href="#explorar" data-testid="link-all-products" className="text-xs font-bold text-[#355c74] flex items-center gap-1 hover:underline">Ver todo <ArrowRight size={14}/></a></div>
      {promotions.isLoading ? <SkeletonGrid/> : promotions.isError ? <Notice icon="error" title="No pudimos cargar los destacados" text="Intenta de nuevo en un momento." action={<button className="btn btn-primary" data-testid="button-retry-promos" onClick={() => promotions.refetch()}>Reintentar</button>}/> : promotions.data?.length ? <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-5">{promotions.data.slice(0,4).map(p => <ProductCard key={p.id} product={p}/>)}</div> : <div className="bg-[#e7efe3] rounded-[24px] p-6 sm:p-9 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div><span className="eyebrow text-[#6c9461]">Próximamente</span><h3 className="font-display text-2xl text-[#294d64] mt-2">Aquí aparecerán las recomendaciones del día.</h3><p className="text-sm text-[#627d7b] mt-2">Mientras tanto, date una vuelta por todo el mercado.</p></div><a href="#explorar" data-testid="link-browse-now" className="btn btn-primary shrink-0">Ver productos <ArrowRight size={15}/></a></div>}
    </section>
    <section id="explorar" className="page-wrap pt-20 scroll-mt-24"><PageHeading eyebrow="El mercado" title="Encuentra algo para ti." description="Busca por nombre o descubre qué están ofreciendo tus vecinos hoy."/>
      <div className="panel p-3 sm:p-4 mb-6"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#72908c]" size={18}/><input data-testid="input-search-products" type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="¿Qué se te antoja hoy?" className="field pl-11 pr-10 h-13"/>{search && <button data-testid="button-clear-search" aria-label="Limpiar búsqueda" onClick={() => setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-[#809492]"><X size={16}/></button>}</div><div className="flex gap-2 overflow-x-auto mt-3 pb-1 scrollbar-none">{categories.map(c => <button key={c} data-testid={`button-category-${c}`} onClick={() => setCategory(c)} className={`chip whitespace-nowrap transition-colors ${category === c ? 'bg-[#355c74] text-white' : 'bg-[#edf2e9] text-[#58716d] hover:bg-[#dce9cf]'}`}>{c}</button>)}</div></div>
      <div className="flex items-center justify-between mb-5"><p data-testid="text-product-count" className="text-xs text-[#718781]">{products.isLoading ? 'Buscando entre vecinos…' : `${products.data?.length || 0} ${products.data?.length === 1 ? 'resultado' : 'resultados'}`}</p><select data-testid="select-sort" className="bg-transparent text-xs font-bold text-[#355c74] focus:outline-none" value={sort} onChange={e => setSort(e.target.value as 'newest' | 'top')}><option value="newest">Más recientes</option><option value="top">Mejor valorados</option></select></div>
      {products.isLoading ? <SkeletonGrid count={8}/> : products.isError ? <Notice icon="error" title="El mercado no cargó" text="Hubo un problema al traer los productos. Podemos intentarlo otra vez." action={<button data-testid="button-retry-products" className="btn btn-primary" onClick={() => products.refetch()}>Reintentar</button>}/> : products.data?.length ? <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-5">{products.data.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <Notice title="Todavía no hay resultados" text={search || category !== 'Todos' ? 'Prueba con otra palabra o categoría. Algo bueno puede estar esperándote.' : 'Sé el primer vecino en publicar algo para compartir.'} action={<button data-testid="button-clear-filters" className="btn btn-primary" onClick={() => {setSearch('');setCategory('Todos');}}>Ver todo el mercado</button>}/>}
    </section>
    <section className="page-wrap pt-20"><div className="bg-[#355c74] rounded-[28px] p-7 sm:p-12 text-[#f7f8ee] grid md:grid-cols-[1fr_auto] items-center gap-6 relative overflow-hidden"><div className="relative z-10"><span className="eyebrow text-[#c3df96]">Tu talento tiene vecinos</span><h2 className="font-display text-3xl sm:text-5xl mt-3 max-w-xl">Eso que haces tan bien, compártelo aquí.</h2><p className="text-[#c5d9d7] mt-3 text-sm max-w-md">Publica en minutos. Tú eliges cuándo estás disponible y coordinas directamente con quien compra.</p></div><Link href="/sell" data-testid="link-cta-sell" className="btn btn-leaf relative z-10">Comenzar a vender <ArrowRight size={16}/></Link><div className="absolute -right-20 -bottom-32 w-80 h-80 rounded-full border-[45px] border-[#497489]"/></div></section>
    <section className="page-wrap pt-20"><div className="flex items-center gap-2 text-[#72995f] eyebrow mb-3"><Star size={15}/> Mejor puntuados</div><h2 className="font-display text-3xl sm:text-4xl text-[#294d64] mb-7">Los favoritos de los vecinos</h2>{topRated.length ? <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-5">{topRated.slice(0,4).map(p => <ProductCard key={p.id} product={p}/>)}</div> : <p className="text-sm text-[#6d8582]">Aquí aparecerán los productos cuando reciban sus primeras opiniones.</p>}</section>
  </>;
}